server {
    listen 80;
    root /usr/share/nginx/html;
    index login.html;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    location / {
        try_files $uri $uri/ /login.html;
    }
}